@startuml
'https://plantuml.com/class-diagram

package "Kernel Density Estimation (KDE)" {

    class KDE {
        + estimateDensity(data: vector, kernelType: kernels, bandwidth: double): vector
    }

    class KernelFunction {
        - function: function
        + evaluate(x: vector, y: vector, bandwidth: double): double
    }

    class KernelType {
        + Gaussian
        + Exponential
        + Laplacian
    }
}

@enduml