@startuml
'https://plantuml.com/class-diagram

package "Kernel Density Estimation (KDE)" {

    class KdeUsingMrpt {
        - KNN_: int {readOnly}
        - N_: int {readOnly}
        - SAMPLES_: int {readOnly}
        - DATA_: Matrix {readOnly}
        - KERNEL_: kernelType {readOnly}
        - mrpt_: Mrpt

        + KdeUsingMrpt(data: Eigen::MatrixXf*, knn: int, samples: int, trees: int, kernel: kernelType)
        + query(q: Eigen::VectorXf*): float
        + ~KdeUsingMrpt()
        -NNContribution(q: Eigen::VectorXf*, ann_list: vector<int>*): inline float
        -SampleContribution(q: Eigen::VectorXf*, ann_list: vector<int>*): inline float
    }

    class KernelFunction {
        - function: function
        + evaluate(x: vector, y: vector, bandwidth: double): double
    }

    class KernelType {
        + Gaussian
        + Exponential
        + Laplacian
    }
}

@enduml